name: pig-hp
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.1
  - pandas=2.2
  - scipy=1.14
  - scikit-learn=1.5
  - matplotlib=3.9
  - openpyxl=3.1
  - lightgbm=4.5
  - xgboost=2.1
  - catboost=1.2
